SELECT * FROM cyber_security.`global_cybersecurity_threats_2015_2024`;


-- Total financial loss by country
-- Total financial loss by country and attack type 
-- Ranking the attack type by total financial loss 
-- Ranking by most security vulnerebility type and average time to resolute the attack 
-- Financial loss over time analyses
-- What is the average loss, number of affected and time to resolute the attack base on targeted industry 
-- Ranking target industry by attack type, the average financial loss and time to resolute the attack 
-- Ranking defense mechanism by targeted industry according to least average financial loss
-- Ranking attack source to targeted industry by frequency of attack and average loss

-- Total financial loss by country in time series 

Select 
      DISTINCT (COUNTRY),
      YEAR AS YEAR,
      SUM(AFFECTED_USERS) AS NUMBER_AFFECTED_USERS,
      CONCAT('$',ROUND(SUM(FINANCIAL_LOSS),2)) AS TOTAL_LOSS_IN_MILLIONS,
      CONCAT('$',ROUND(SUM(SUM(FINANCIAL_LOSS)) OVER (PARTITION BY COUNTRY ORDER BY YEAR),2)) AS CUMULATIVE
FROM global_cybersecurity_threats_2015_2024
GROUP BY YEAR, COUNTRY;


-- Global combined Financial loss over time AND Y/Y Differences 

WITH CTE_SUM_LOSS AS (
SELECT 
      YEAR AS YEAR,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS_MILLIONS
FROM GLOBAL_CYBERSECURITY_THREATS_2015_2024
GROUP BY YEAR
ORDER BY YEAR
)
SELECT 
      *,
      ROUND(TOTAL_LOSS_MILLIONS - LAG(TOTAL_LOSS_MILLIONS) OVER (),2) AS PREVIOUS_DIFFERENCES
FROM CTE_SUM_LOSS


-- Total financial loss by country and attack type 

SELECT 
      DISTINCT (COUNTRY),
      TARGET_INDUSTRY,
      ATTACK_TYPE,
      COUNT(ATTACK_TYPE) AS TOTAL_ATTACK,
      CONCAT('$',ROUND(AVG(FINANCIAL_LOSS),2))  AS AVG_LOSS,
      CONCAT('$',MAX(FINANCIAL_LOSS)) AS MAX_LOSS,
      CONCAT('$',ROUND(SUM(FINANCIAL_LOSS)),2) AS TOTAL_LOSS_IN_MILLIONS,
      DENSE_RANK () OVER (PARTITION BY COUNTRY ORDER BY SUM(FINANCIAL_LOSS) DESC) AS RANK_NUM
FROM global_cybersecurity_threats_2015_2024
GROUP BY COUNTRY,TARGET_INDUSTRY,ATTACK_TYPE;

-- Ranking the attack type by total financial loss

SELECT 
      DISTINCT(ATTACK_TYPE),
      YEAR,
      CONCAT('$',ROUND(SUM(FINANCIAL_LOSS),2)) AS TOTAL_LOSS,
      SUM(AFFECTED_USERS) AS TOTAL_USERS_AFFECTED,
      DENSE_RANK () OVER (PARTITION BY ATTACK_TYPE ORDER BY YEAR) AS RANK_NUM
FROM global_cybersecurity_threats_2015_2024
GROUP BY ATTACK_TYPE, YEAR;

-- What is the TOP 10 average loss, number of affected and time to resolute the attack base on targeted industry among affected countries

SELECT * 
FROM  (SELECT 
      DISTINCT(TARGET_INDUSTRY),
      COUNTRY,
      ATTACK_TYPE,
      COUNT(ATTACK_TYPE) AS TOTAL_ATTACK,
      ROUND(AVG(FINANCIAL_LOSS),2) AS AVG_LOSS,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS,
      ROUND(AVG(RESOLUTION_TIME),1) AS AVG_RESOLUTION_TIME_HOURS,
      ROUND(AVG(AFFECTED_USERS),2) AS AVG_NUMBERS_USERS_AFFECTED,
      ROW_NUMBER () OVER (PARTITION BY TARGET_INDUSTRY ORDER BY SUM(FINANCIAL_LOSS) DESC) AS ROW_NUM
FROM global_cybersecurity_threats_2015_2024
GROUP BY TARGET_INDUSTRY, COUNTRY, ATTACK_TYPE) A
WHERE A.ROW_NUM BETWEEN 1 AND 10;


-- Ranking defense mechanism by targeted industry according to least average financial loss

SELECT 
      DISTINCT(TARGET_INDUSTRY),
      DEFENSE_MECHANISM,
      COUNT(DEFENSE_MECHANISM) AS TOTAL_USED,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS,
      ROUND(AVG(FINANCIAL_LOSS),2) AS AVG_LOSS,
      ROUND(AVG(RESOLUTION_TIME),2) AS AVG_RESOLUTION_TIME_HOURS,
      ROW_NUMBER () OVER (PARTITION BY TARGET_INDUSTRY ORDER BY SUM(FINANCIAL_LOSS) ASC ) AS ROW_NUM
FROM global_cybersecurity_threats_2015_2024
GROUP BY TARGET_INDUSTRY,DEFENSE_MECHANISM;


-- Rank of highest and lowest probable attack type base on security vulnerability by attack source

SELECT 
      DISTINCT(ATTACK_SOURCE),
      SECURITY_VULNERABILITY,
      ATTACK_TYPE,
      COUNT(ATTACK_TYPE) AS TOTAL_ATTACK,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS,
      ROUND(SUM(SUM(FINANCIAL_LOSS)) OVER (PARTITION BY ATTACK_SOURCE ORDER BY COUNT(ATTACK_TYPE)),2) AS CUMULATIVE_LOSS,
      ROW_NUMBER () OVER (PARTITION BY ATTACK_SOURCE  ORDER BY COUNT(ATTACK_TYPE)) AS LEAST_PROBABILITY_SECURITY_VUL_ATTACK_TYP,
      ROW_NUMBER () OVER (PARTITION BY ATTACK_SOURCE  ORDER BY COUNT(ATTACK_TYPE) DESC) AS HIGHEST_PROBABILITY_SECURITY_VUL_ATTACK_TYP
FROM GLOBAL_CYBERSECURITY_THREATS_2015_2024
GROUP BY ATTACK_SOURCE, SECURITY_VULNERABILITY, ATTACK_TYPE;


-- procedure for accuquring rank based data on highest attack type on distinct target industry

DELIMITER $$
CREATE PROCEDURE p_rank_highest_attack_type (IN p_row_num INT)
BEGIN
   SELECT * 
FROM  (SELECT 
	  DISTINCT(TARGET_INDUSTRY),
      ATTACK_TYPE,
      COUNT(ATTACK_TYPE) AS TOTAL_ATTACK,
      ROUND(AVG(FINANCIAL_LOSS),2) AS AVG_LOSS,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS,
      AVG(RESOLUTION_TIME) AS AVG_RESOLUTION_TIME_HOURS,
      ROUND(AVG(AFFECTED_USERS),2) AS AVG_NUMBERS_USERS_AFFECTED,
      ROW_NUMBER () OVER (PARTITION BY TARGET_INDUSTRY ORDER BY COUNT(ATTACK_TYPE) DESC) AS ROW_NUM
FROM global_cybersecurity_threats_2015_2024
GROUP BY TARGET_INDUSTRY, ATTACK_TYPE) A
WHERE p_row_num = A.row_num;
end $$
DELIMITER ;

      
-- procedure for accuquring rank based data on least loss by individual defense mechanism at distinct target industry     

DELIMITER $$
CREATE PROCEDURE p_rank_best_defense_mechanism (IN p_row_num INT)
BEGIN

SELECT * 
FROM 
    (SELECT 
      DISTINCT(TARGET_INDUSTRY),
      DEFENSE_MECHANISM,
      COUNT(DEFENSE_MECHANISM) AS TOTAL_USED,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS,
      ROUND(AVG(FINANCIAL_LOSS),2) AS AVG_LOSS,
      ROUND(AVG(RESOLUTION_TIME),2) AS AVG_RESOLUTION_TIME_HOURS,
      ROW_NUMBER () OVER (PARTITION BY TARGET_INDUSTRY ORDER BY SUM(FINANCIAL_LOSS) ASC ) AS ROW_NUM
FROM global_cybersecurity_threats_2015_2024
GROUP BY TARGET_INDUSTRY,DEFENSE_MECHANISM) A
WHERE P_ROW_NUM = A.ROW_NUM;
END $$
DELIMITER ;


-- procedure for finding rank of highest and lowest probable attack type base on security vulnerability by attack source

DELIMITER $$
CREATE PROCEDURE p_rank_security_vulnerability_attack_type (IN P_RANK_LEAST_PROBABILITY_SECURITY_VUL_ATTACK_TYP INT , IN P_RANK_HIGHEST_PROBABILITY_SECURITY_VUL_ATTACK_TYP INT)
BEGIN
SELECT *
FROM (SELECT 
      DISTINCT(ATTACK_SOURCE),
      SECURITY_VULNERABILITY,
      ATTACK_TYPE,
      COUNT(ATTACK_TYPE) AS TOTAL_ATTACK,
      ROUND(SUM(FINANCIAL_LOSS),2) AS TOTAL_LOSS,
      ROUND(SUM(SUM(FINANCIAL_LOSS)) OVER (PARTITION BY ATTACK_SOURCE ORDER BY COUNT(ATTACK_TYPE)),2) AS CUMULATIVE_LOSS,
      ROW_NUMBER () OVER (PARTITION BY ATTACK_SOURCE  ORDER BY COUNT(ATTACK_TYPE)) AS LEAST_PROBABILITY_SECURITY_VUL_ATTACK_TYP,
      ROW_NUMBER () OVER (PARTITION BY ATTACK_SOURCE  ORDER BY COUNT(ATTACK_TYPE) DESC) AS HIGHEST_PROBABILITY_SECURITY_VUL_ATTACK_TYP
FROM GLOBAL_CYBERSECURITY_THREATS_2015_2024
GROUP BY ATTACK_SOURCE, SECURITY_VULNERABILITY, ATTACK_TYPE) A
WHERE P_RANK_LEAST_PROBABILITY_SECURITY_VUL_ATTACK_TYP = A.LEAST_PROBABILITY_SECURITY_VUL_ATTACK_TYP OR P_RANK_HIGHEST_PROBABILITY_SECURITY_VUL_ATTACK_TYP = A.HIGHEST_PROBABILITY_SECURITY_VUL_ATTACK_TYP;
END$$
DELIMITER ;














